server:
    port: 8083
spring:
    application:
        name: OnlineRetailSystem
    security:
        user:
            name: user
            password: pass
    cloud:
        config:
            url: http://localhost:8888
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: admin
        url: jdbc:mysql://localhost:3306/online_retail_system?useLegacyDatetimeCode=false&serverTimezone=UTC
        username: admin
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

app:
    name: Online Retail System
    server:
        name: OnlineRetailSystem_Group1_Server
        url: http://localhost:8080
    version: 1.0

logging:
    level:
        org:
            springframework: INFO
        root: INFO

